name: Section 4.2 partitioned heat conduction
on:
  release:
    types: [published]
  workflow_dispatch:
  pull_request:

jobs:
  section_4_2_partitioned:
    name: Perform experiments from Section 4.2 (partitioned)
    strategy:
      matrix:
        experiment:
        - name: Figure 13 IE, p=3
          args: '--experiment sincos -w 6 -s 1 -wd 3 -sb 5 5 -dt 1 -tss BackwardEuler BackwardEuler --exchange-substeps -o results/Fig13/data/IE_3.csv'
        - name: Figure 13 GL(2), p=2
          args: '--experiment sincos -w 6 -s 1 -wd 2 -sb 5 5 -dt 1 -tss GaussLegendre2 GaussLegendre2 --exchange-substeps -o results/Fig13/data/GL2_2.csv'
        - name: Figure 13 GL(2), p=3
          args: '--experiment sincos -w 6 -s 1 -wd 3 -sb 5 5 -dt 1 -tss GaussLegendre2 GaussLegendre2 --exchange-substeps -o results/Fig13/data/GL2_3.csv'
        - name: Figure 13 GL(2), p=5
          args: '--experiment sincos -w 6 -s 1 -wd 5 -sb 5 5 -dt 1 -tss GaussLegendre2 GaussLegendre2 --exchange-substeps -o results/Fig13/data/GL2_5.csv'
        - name: Figure 13 GL(3), p=3
          args: '--experiment sincos -w 6 -s 1 -wd 3 -sb 5 5 -dt 1 -tss GaussLegendre3 GaussLegendre3 --exchange-substeps -o results/Fig13/data/GL3_3.csv'
        - name: Figure 13 GL(3), p=5
          args: '--experiment sincos -w 6 -s 1 -wd 5 -sb 5 5 -dt 1 -tss GaussLegendre3 GaussLegendre3 --exchange-substeps -o results/Fig13/data/GL3_5.csv'
        - name: Figure 13 LIIIC(3), p=2
          args: '--experiment sincos -w 6 -s 1 -wd 2 -sb 5 5 -dt 1 -tss LobattoIIIC3 LobattoIIIC3 --exchange-substeps -o results/Fig13extra/data/LIIIC3_2.csv'
        - name: Figure 13 LIIIC(3), p=3
          args: '--experiment sincos -w 6 -s 1 -wd 3 -sb 5 5 -dt 1 -tss LobattoIIIC3 LobattoIIIC3 --exchange-substeps -o results/Fig13extra/data/LIIIC3_3.csv'
        - name: Figure 13 LIIIC(3), p=5
          args: '--experiment sincos -w 6 -s 1 -wd 5 -sb 5 5 -dt 1 -tss LobattoIIIC3 LobattoIIIC3 --exchange-substeps -o results/Fig13extra/data/LIIIC3_5.csv'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./partitioned-heat-conduction
    container: precice/precice:3.2.0
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          apt-get -qq update
          apt-get -qq install software-properties-common python3-dev python3-pip python3.12-venv git apt-utils pkg-config
          add-apt-repository -y ppa:fenics-packages/fenics
          apt-get -qq install --no-install-recommends fenics
          rm -rf /var/lib/apt/lists/*
      - name: Create venv
        run: |
          ./make-venv.sh
      - name: Activate venv
        # see https://stackoverflow.com/a/74669486
        run: |
          . .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
      - name: Run tutorial
        run: |
          python3 doConvergenceStudy.py precice-config-template.xml --silent --executor Github ${{matrix.experiment.args}}
      - name: Store results
        uses: actions/upload-artifact@v4
        with:
          name: partitioned-heat-conduction-convergence ${{ matrix.experiment.name }}
          path: |
            # working directory is ignored by actions/upload-artifact
            ./partitioned-heat-conduction/results

  section_4_2_monolithic:
    name: Perform experiments from Section 4.2 (monolithic)
    strategy:
      matrix:
        experiment:
        - name: Figure 13 IE, mono
          args: '--experiment sincos -s 6 -dt 0.2 -tss BackwardEuler -o results/Fig13/data/IE_mono.csv'
        - name: Figure 13 GL(2), mono
          args: '--experiment sincos -s 6 -dt 0.2 -tss GaussLegendre2 -o results/Fig13/data/GL2_mono.csv'
        - name: Figure 13 GL(3), mono
          args: '--experiment sincos -s 6 -dt 0.2 -tss GaussLegendre3 -o results/Fig13/data/GL3_mono.csv'
        - name: Figure 13 LIIIC(3), mono
          args: '--experiment sincos -s 6 -dt 0.2 -tss GaussLegendre3 -o results/Fig13extra/data/LIIIC3_mono.csv'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./partitioned-heat-conduction
    container: precice/precice:3.2.0
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          apt-get -qq update
          apt-get -qq install software-properties-common python3-dev python3-pip python3.12-venv git apt-utils pkg-config
          add-apt-repository -y ppa:fenics-packages/fenics
          apt-get -qq install --no-install-recommends fenics
          rm -rf /var/lib/apt/lists/*
      - name: Create venv
        run: |
          ./make-venv.sh
      - name: Activate venv
        # see https://stackoverflow.com/a/74669486
        run: |
          . .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
      - name: Run tutorial
        run: |
          python3 doConvergenceStudyMonolithic.py --silent --executor Github ${{matrix.experiment.args}}
      - name: Store results
        uses: actions/upload-artifact@v4
        with:
          name: partitioned-heat-conduction-convergence ${{ matrix.experiment.name }}
          path: |
            # working directory is ignored by actions/upload-artifact
            ./partitioned-heat-conduction/results

  visualize:
    name: Create plots to visualize experiments from Section 4.2
    needs: 
      - section_4_2_partitioned
      - section_4_2_monolithic
    runs-on: ubuntu-latest
    container: 
      image: benjaminrodenberg/latex:wi-paper
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Download results from stage "experiment"
        uses: actions/download-artifact@v5
        with:
          pattern: partitioned-heat-conduction*
          merge-multiple: true
          path: artifacts
      - name: Show structure for debugging
        run: |
          ls -R artifacts
      - name: Replace pre-computed results with newly computed ones
        run: |
          rm -r plotting/partitioned-heat-conduction/Fig13/data
          mv artifacts/Fig13/data plotting/partitioned-heat-conduction/Fig13/data
      - name: Install Python dependencies
        working-directory: plotting
        run: pip install --break-system-packages -r requirements.txt
      - name: Create visualizations
        working-directory: plotting/partitioned-heat-conduction
        run: make
      - name: Store results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: visualizations
          path: |
            plotting/partitioned-heat-conduction/Fig13/main.pdf

  merge:
    name: Merge output artifacts
    runs-on: ubuntu-latest
    needs: 
      - section_4_2_partitioned
      - section_4_2_monolithic
    steps:
      - name: Merge results
        uses: actions/upload-artifact/merge@v4
        with:
          name: partitioned-heat-conduction