name: Section 4.3 perpendicular flap
on:
  release:
    types: [published]
  workflow_dispatch:
  pull_request:

jobs:
  section_4_3:
    name: Perform experiments from Section 4.3
    strategy:
      matrix:
        experiment:
        - name: Figure 15
          args: 'configs/Fig15.csv -o results/Fig15/data/result.csv'
        - name: Figure 16
          args: 'configs/Fig16.csv -o results/Fig16/data/result.csv'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: experiments/perpendicular-flap
    # built using tools/docker/fenics-openfoam/Dockerfile
    container: benjaminrodenberg/fenics-openfoam:3.2.0
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Update $HOME
        run: echo "HOME=/root" >> "$GITHUB_ENV"
      - name: Activate OpenFOAM # From https://github.com/gerlero/setup-openfoam/blob/68e0bf96c7f2aac1a100291a5d61fff934a472a8/action.yml#L54-L69
        run: |
          old_path="$PATH"
          source /usr/lib/openfoam/openfoam2412/etc/bashrc || true

          for var in "${!WM_@}"; do
            echo "$var=${!var}" >> "$GITHUB_ENV"
          done

          for var in "${!FOAM_@}"; do
            echo "$var=${!var}" >> "$GITHUB_ENV"
          done

          echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH" >> "$GITHUB_ENV"

          echo "${PATH/%:$old_path}" >> "$GITHUB_PATH"
      - name: Install Dependencies
        run: |
          apt-get -qq update
          apt-get -qq install python3-dev python3-pip python3.12-venv git apt-utils pkg-config
          rm -rf /var/lib/apt/lists/*
      - name: Create venv
        run: |
          ./make-venv.sh
      - name: Create venv for solid-fenics
        run: |
          cd solid-fenics
          python3 -m venv --system-site-packages .venv
          . .venv/bin/activate
          pip install -r requirements.txt
      - name: Run tutorial
        run: |
          . .venv/bin/activate
          python3 doConvergenceStudy.py precice-config.xml.jinja2 --silent --executor Github ${{matrix.experiment.args}}
      - name: Store results
        uses: actions/upload-artifact@v4
        with:
          name: perpendicular-flap ${{ matrix.experiment.name }}
          path: |
            # working directory is ignored by actions/upload-artifact
            experiments/perpendicular-flap/results

  visualize:
    name: Create plots to visualize experiments from Section 4.3
    needs: 
      - section_4_3
    runs-on: ubuntu-latest
    container: 
      image: benjaminrodenberg/latex:wi-paper
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Download results from stage "experiment"
        uses: actions/download-artifact@v5
        with:
          pattern: perpendicular-flap*
          merge-multiple: true
          path: artifacts
      - name: Show structure for debugging
        run: |
          ls -R artifacts
      - name: Replace pre-computed results with newly computed ones
        run: |
          rm -r plotting/perpendicular-flap/Fig15/data
          mv artifacts/Fig15/data plotting/perpendicular-flap/Fig15/data
          rm -r plotting/perpendicular-flap/Fig16/data
          mv artifacts/Fig16/data plotting/perpendicular-flap/Fig16/data
      - name: Install Python dependencies
        working-directory: plotting
        run: pip install --break-system-packages -r requirements.txt
      - name: Create visualizations
        working-directory: plotting/perpendicular-flap
        run: make
      - name: Store results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: visualizations
          path: |
            plotting/perpendicular-flap/Fig15/main.pdf
            plotting/perpendicular-flap/Fig16/main.pdf

  merge:
    name: Merge output artifacts
    runs-on: ubuntu-latest
    needs: section_4_3
    steps:
      - name: Merge results
        uses: actions/upload-artifact/merge@v4
        with:
          name: perpendicular-flap

  publish-pages:
    needs: 
      - merge
      - visualize
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download merge output
        uses: actions/download-artifact@v4
        with:
          name: merge-output
          path: pages/perpendicular-flap/results

      - name: Download visualizations
        uses: actions/download-artifact@v4
        with:
          name: visualizations
          path: pages/perpendicular-flap/visualizations

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: pages/perpendicular-flap/
